In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
dataset = pd.read_csv("data.csv")
X=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [5]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
4  396.90   5.33

In [6]:
y


0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [16]:
X = np.nan_to_num(X, nan=0)

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [18]:
print(boston.target)

array([[2.98500e-02, 0.00000e+00, 2.18000e+00, ..., 1.87000e+01,
        3.94120e+02, 5.21000e+00],
       [1.31580e-01, 0.00000e+00, 1.00100e+01, ..., 1.78000e+01,
        3.93300e+02, 1.20400e+01],
       [1.71420e-01, 0.00000e+00, 6.91000e+00, ..., 1.79000e+01,
        3.96900e+02, 1.02100e+01],
       ...,
       [1.50100e-02, 8.00000e+01, 2.01000e+00, ..., 1.70000e+01,
        3.90940e+02, 5.99000e+00],
       [1.11604e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        1.09850e+02, 2.32700e+01],
       [2.28760e-01, 0.00000e+00, 8.56000e+00, ..., 2.09000e+01,
        7.08000e+01, 1.06300e+01]])

array([[9.17800e-02, 0.00000e+00, 4.05000e+00, ..., 1.66000e+01,
        3.95500e+02, 9.04000e+00],
       [5.64400e-02, 4.00000e+01, 6.41000e+00, ..., 1.76000e+01,
        3.96900e+02, 3.53000e+00],
       [1.05740e-01, 0.00000e+00, 2.77400e+01, ..., 2.01000e+01,
        3.90110e+02, 1.80700e+01],
       ...,
       [5.26930e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.82000e+02, 4.63000e+00],
       [5.58107e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        1.00190e+02, 1.62200e+01],
       [9.92485e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.88520e+02, 1.64400e+01]])

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [22]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [24]:
X_train


array([[-0.41425879, -0.50512499, -1.29214218, ...,  0.18727079,
         0.39651419, -1.01531611],
       [-0.40200818, -0.50512499, -0.16208345, ..., -0.21208981,
         0.3870674 , -0.05366252],
       [-0.39721053, -0.50512499, -0.60948856, ..., -0.16771641,
         0.42854113, -0.31132373],
       ...,
       [-0.41604586,  3.03838247, -1.3166773 , ..., -0.56707702,
         0.35987906, -0.90549329],
       [ 0.92611293, -0.50512499,  1.00549958, ...,  0.8528718 ,
        -2.87841346,  1.52750437],
       [-0.39030549, -0.50512499, -0.37135358, ...,  1.16348561,
        -3.32828832, -0.25218837]])

In [12]:
#Saving the scaled file
import pickle
pickle.dump(scaler,open('scaling.pkl','wb'))

In [13]:
from sklearn.linear_model import LinearRegression

In [23]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [25]:
print(regression.coef_)

[-1.17863505  0.97151432 -0.02058714  0.86427804 -2.05973053  1.82797606
  0.25137481 -3.13152224  2.40735579 -1.55894081 -2.28483141  0.94333962
 -4.78146578]


In [26]:
reg_pred=regression.predict(X_test)

In [27]:
reg_pred


array([29.87567302, 36.90637196, 14.67378503, 25.64533935, 18.3269372 ,
       23.42584316, 17.80208746, 12.41795653, 23.53120031, 21.17538113,
       25.74109808, 19.32949764, -5.77626043, 21.62593996, 20.84762275,
       24.61138148, 20.32281203,  6.70777672, 39.11884601, 17.28600376,
       27.71892858, 30.51195706, 11.30626985, 23.36070907, 18.53143731,
       17.56613172, 23.84011787, 13.25252366, 23.24247548, 20.22514335,
       24.62196765, 25.38743145, 23.21488099, 20.92856446, 16.61167235,
       18.41232504, 30.19663245, 21.14503679, 24.23481093, 24.44220408,
       14.88962207, 32.32707404, 40.94580289, 18.76016819, 27.74385656,
       18.11075595, 14.79268283, 25.4048608 , 20.27478416, 31.11824787,
       22.54713946, 34.13417596, 15.45836234, 25.67521369, 38.72114771,
       22.63631205, 18.80660624, 33.16830078, 25.03210128, 14.0238557 ,
        9.25428122, 29.91024418, 31.84618345, 17.56593587, 21.2258739 ,
       18.25413188, 19.67688144, 26.69838189, 31.57680333, 12.19

In [28]:
plt.scatter(y_test,reg_pred)

In [29]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_test,reg_pred))
print(mean_squared_error(y_test,reg_pred))
print(np.sqrt(mean_squared_error(y_test,reg_pred)))

3.38703203443881
23.324844389126998
4.829580146257746


In [30]:
from sklearn.metrics import r2_score
score=r2_score(y_test,reg_pred)
print(score)


0.6869698646745581


In [32]:
input_data = X_train[0].reshape(1,-1)
scaler.transform(input_data.reshape(1,-1))

array([[ -0.4677396 ,  -0.52749891,  -1.79325642,  -1.36081455,
        -12.07564425,  -6.19505403,  -2.50360739,  -1.26434844,
         -1.18037974,  -2.4545243 ,  -8.02745672,  -4.13937047,
         -1.89183113]])

In [33]:
regression.predict(scaler.transform(input_data.reshape(1,-1)))

array([63.26073359])

In [34]:
import pickle
pickle.dump(regression,open('regmodel.pkl','wb'))
pickled_model=pickle.load(open('regmodel.pkl','rb'))
## Prediction
pickled_model.predict(scaler.transform(input_data.reshape(1,-1)))


array([63.26073359])