In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
dataset = pd.read_csv("data.csv")

X=dataset.iloc[:,:-2]
y=dataset.iloc[:,-2]

In [10]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  
0  396.90  
1  396.90  
2  392.83  
3  394.63  
4  396.90

In [11]:
y


0      4.98
1      9.14
2      4.03
3      2.94
4      5.33
       ... 
501    9.67
502    9.08
503    5.64
504    6.48
505    7.88
Name: LSTAT, Length: 506, dtype: float64

In [20]:
X = np.nan_to_num(X, nan=0)

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [23]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [24]:
X_train


array([[-0.41425879, -0.50512499, -1.29214218, ..., -1.11279004,
         0.18727079,  0.39651419],
       [-0.40200818, -0.50512499, -0.16208345, ...,  0.15008778,
        -0.21208981,  0.3870674 ],
       [-0.39721053, -0.50512499, -0.60948856, ..., -1.0466393 ,
        -0.16771641,  0.42854113],
       ...,
       [-0.41604586,  3.03838247, -1.3166773 , ..., -0.76399522,
        -0.56707702,  0.35987906],
       [ 0.92611293, -0.50512499,  1.00549958, ...,  1.5572945 ,
         0.8528718 , -2.87841346],
       [-0.39030549, -0.50512499, -0.37135358, ..., -0.13857001,
         1.16348561, -3.32828832]])

In [25]:
#Saving the scaled file
import pickle
pickle.dump(scaler,open('scaling.pkl','wb'))

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [28]:
print(regression.coef_)

[ 0.76139115  0.26724646  0.8061436  -0.63621633  1.82180511 -2.17844082
  1.66096428  0.65181713  0.21704876 -0.05042198  0.80103655 -0.61055547]


In [29]:
reg_pred=regression.predict(X_test)

In [15]:
reg_pred


array([ 9.886994  ,  4.14380964, 16.92829226,  7.08969275, 17.51139614,
       10.79688636, 13.24122407, 16.17190597, 14.82488901, 13.19131913,
       10.83499628, 12.49942323, 27.23747211,  9.85227724, 12.74619193,
       13.07653955, 16.16837003, 21.64177518,  2.79841699, 18.44779676,
        7.28488106,  7.16879524, 15.32884427, 11.93389241, 18.92969506,
       18.16405224,  9.39662787, 19.79920608, 10.46731354, 13.28672462,
       12.00468396,  9.72247352, 15.89128016, 20.561999  , 16.68148246,
       19.87469845,  7.60039629, 11.11960028,  8.44388667,  6.69997219,
       14.29512721,  8.53882153,  2.76268757,  9.62793144,  8.91518051,
       18.88804312, 15.28449419,  6.28613725, 15.3067167 ,  8.70849155,
       12.11927142,  5.18211722, 13.90431042, 10.55554135,  5.77266504,
       13.39223425, 18.46605946,  6.68312382,  8.15602036, 12.70146229,
       24.03913093,  5.693047  ,  6.69071573, 12.77902308,  8.70916671,
       12.30772092, 17.32027011,  7.7610065 ,  6.62908316, 20.65

In [30]:
plt.scatter(y_test,reg_pred)

In [31]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_test,reg_pred))
print(mean_squared_error(y_test,reg_pred))
print(np.sqrt(mean_squared_error(y_test,reg_pred)))

3.10680516580942
18.462343426343498
4.2967829158969035


In [32]:
from sklearn.metrics import r2_score
score=r2_score(y_test,reg_pred)
print(score)


0.6416913662493691


In [33]:
input_data = X_train[0].reshape(1,-1)
scaler.transform(input_data.reshape(1,-1))

array([[ -0.4677396 ,  -0.52749891,  -1.79325642,  -1.36081455,
        -12.07564425,  -6.19505403,  -2.50360739,  -1.26434844,
         -1.18037974,  -2.4545243 ,  -8.02745672,  -4.13937047]])

In [34]:
regression.predict(scaler.transform(input_data.reshape(1,-1)))

array([-6.17767199])

In [35]:
import pickle
pickle.dump(regression,open('regmodel.pkl','wb'))
pickled_model=pickle.load(open('regmodel.pkl','rb'))
## Prediction
pickled_model.predict(scaler.transform(input_data.reshape(1,-1)))


array([-6.17767199])